### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by mibblemerps**
Whilst the Realms endpoint isn't fully functional yet, a 1.8 client will now recognize it as a real Realms endpoint.

### CODE REVIEW

**Comment by BadBreath69** [comment]
Soooooo, does this work yet? If so, please create a  wiki.

**Comment by mibblemerps** [comment]
@harmjanhaisma Heh, I wished it worked yet... once it's in a usable state, I'll be certain to create a wiki.

The progress is a bit slow since I've got to reverse engineer Minecraft Realms (wiki.vg's documentation is out of date)...

**Comment by BadBreath69** [comment]
Isnt all the data in the realms.jar (library)

**Comment by harmjanhaisma** [comment]
Your could decompile it

**Comment by mibblemerps** [comment]
I actually am doing that, but it is a slow process nonetheless. ;)

**Comment by harmjanhaisma** [comment]
I will see if i can contribute, but Java checks the link if your edit the host file.

**Pull request merged**
